# Generated by Django 4.1.3 on 2022-12-04 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('wiki_url', models.URLField(max_length=300, null=True, unique=True)),
                ('release_date', models.IntegerField(null=True)),
                ('snippet', models.TextField(null=True)),
                ('female_lead', models.CharField(max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rangeStart', models.IntegerField(null=True)),
                ('rangeEnd', models.IntegerField(null=True)),
                ('books', models.ManyToManyField(blank=True, related_name='times', to='toppixapi.book')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50, null=True)),
                ('books', models.ManyToManyField(blank=True, related_name='countries', to='toppixapi.book')),
            ],
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent', models.CharField(choices=[('AF', 'Africa'), ('AN', 'Antarctica'), ('AS', 'Asia'), ('OZ', 'Oceania'), ('EU', 'Europe'), ('SA', 'South America'), ('NA', 'North America'), ('EL', 'Elsewhere'), ('UN', 'Unknown')], default='UN', max_length=2)),
                ('books', models.ManyToManyField(blank=True, related_name='continents', to='toppixapi.book')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('gender', models.CharField(choices=[('N', 'Non-binary'), ('F', 'Female'), ('M', 'Male'), ('U', 'Unknown')], default='F', max_length=1)),
                ('age', models.IntegerField(null=True)),
                ('age_range', models.CharField(choices=[('KI', 'Kid'), ('TE', 'Teen'), ('YA', 'Young Adult'), ('AD', 'Adult'), ('ES', 'Early Senior'), ('OS', 'Older Senior'), ('OL', 'Old')], default='AD', max_length=2)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='toppixapi.book')),
            ],
        ),
    ]
